In [2]:
import pandas as pd
import pyodbc
from sqlalchemy import create_engine
import os

In [3]:
data = "IndiaVotes_PC__All_States_2014.csv"
df = pd.read_csv(data)
df.head()

,PC Name,No,Type,State,Winning Candidate,Party,Electors,Votes,Turnout,Margin,Margin %
0,Adilabad,1,ST,Telangana,Godam Nagesh,Telangana Rashtra Samithi,1386233,1045839,75.4 %,171290,16.4%
1,Agra,18,SC,Uttar Pradesh [2000 Onwards],Dr. Ram Shankar Katheria,Bharatiya Janta Party,1814739,1070400,59.0 %,300263,28.1%
2,Ahmadnagar,37,GEN,Maharashtra,Gandhi Dilipkumar Mansukhlal,Bharatiya Janta Party,1699408,1062318,62.5 %,209122,19.7%
3,Ahmedabad East,7,GEN,Gujarat,Paresh Rawal,Bharatiya Janta Party,1601832,985525,61.5 %,326633,33.1%
4,Ahmedabad West,8,SC,Gujarat,Dr. Kirit P Solanki,Bharatiya Janta Party,1534400,964609,62.9 %,320311,33.2%

In [4]:
#Create SQL Engine
rds_connection_string = "root:Soms@1411@localhost:3306/IndianGeneralElection2014"
engine = create_engine(f'mysql://{rds_connection_string}')

In [5]:
engine.table_names()

['IndiaVotes_PC_All_States_2014']

In [6]:
df.to_sql(name='IndiaVotes_PC_All_States_2014', con=engine, if_exists='append', index=False)

In [7]:
pd.read_sql_query('select * from IndiaVotes_PC_All_States_2014', con=engine).head()

,PC Name,No,Type,State,Winning Candidate,Party,Electors,Votes,Turnout,Margin,Margin %
0,Adilabad,1,ST,Telangana,Godam Nagesh,Telangana Rashtra Samithi,1386233,1045839,75.4 %,171290,16.4%
1,Agra,18,SC,Uttar Pradesh [2000 Onwards],Dr. Ram Shankar Katheria,Bharatiya Janta Party,1814739,1070400,59.0 %,300263,28.1%
2,Ahmadnagar,37,GEN,Maharashtra,Gandhi Dilipkumar Mansukhlal,Bharatiya Janta Party,1699408,1062318,62.5 %,209122,19.7%
3,Ahmedabad East,7,GEN,Gujarat,Paresh Rawal,Bharatiya Janta Party,1601832,985525,61.5 %,326633,33.1%
4,Ahmedabad West,8,SC,Gujarat,Dr. Kirit P Solanki,Bharatiya Janta Party,1534400,964609,62.9 %,320311,33.2%

In [8]:
from pytrends.request import TrendReq # Pseudo API for Google Trends (https://pypi.org/project/pytrends/)

In [23]:
partysummary = os.path.join('output','PartySummary.csv')
df = pd.read_csv(partysummary)
df.head(10)

,Party,Total Contestants,Won,Second,Third,Party Votes,Valid Votes %,Valid Votes % (Contested),AC Leads,AC Second,AC Third
0,Bharatiya Janta Party,428,282,54,78,171657549,31.3%,40%,1883,550,601
1,Indian National Congress,464,44,224,66,106938242,19.5%,22.6%,550,1748,531
2,All India Anna Dravida Munnetra Kazhagam,40,37,1,2,18115825,3.3%,44.4%,222,16,24
3,All India Trinamool Congress,131,34,3,7,21259681,3.9%,15.4%,215,55,90
4,Biju Janata Dal,21,20,1,0,9491497,1.7%,44.8%,116,26,5
5,Shiv Sena,58,18,2,0,10262982,1.9%,18%,100,19,1
6,Telugu Desam,30,16,8,6,14094545,2.6%,40.5%,104,67,33
7,Telangana Rashtra Samithi,17,11,2,1,6736490,1.2%,34.9%,67,22,17
8,Communist Party Of India (MARXIST),93,9,30,9,17986773,3.3%,18.4%,118,194,69
9,Yuvajana Sramika Rythu Congress Party,38,9,17,0,13991280,2.6%,32.1%,72,110,2

In [54]:
pytrends = TrendReq(hl='en-US', tz=360)
queries_list = ['BJP', 'Congress', 'AIADMK', 'trinamool congress', 'BJD']
queries_list
pytrends.build_payload(queries_list, timeframe='today 3-m', geo='IN', gprop='news')
Party_group1 = pytrends.interest_over_time()
Party_group1.reset_index(level=0, inplace=True)
Party_group1

         date  BJP  Congress  AIADMK  trinamool congress  BJD  isPartial
0  2019-02-08   13         8       0                   0    0      False
1  2019-02-09   19        17       0                   0    0      False
2  2019-02-10   16        13       0                   0    0      False
3  2019-02-11   18        18       0                   0    0      False
4  2019-02-12   28        14       4                   0    0      False
5  2019-02-13   25        21       4                   0    0      False
6  2019-02-14   27        12       4                   0    0      False
7  2019-02-15   15         7       3                   0    0      False
8  2019-02-16   19        14       3                   0    0      False
9  2019-02-17    7        13       0                   0    0      False
10 2019-02-18   20         9      11                   0    0      False
11 2019-02-19   33        17       6                   0    0      False
12 2019-02-20   21        15       0                   0    4      False
13 2019-02-21   24        11       4                   0    0      False
14 2019-02-22   16        19       4                   0    4      False
15 2019-02-23   24        22       6                   4    0      False
16 2019-02-24   12        10       0                   0    0      False
17 2019-02-25   14        14       0                   0    0      False
18 2019-02-26   11         7       0                   0    3      False
19 2019-02-27    8        14       5                   0    0      False
20 2019-02-28   10        20       0                   0    0      False
21 2019-03-01    7         8       3                   0    0      False
22 2019-03-02   14        18       4                   0    4      False
23 2019-03-03   11        13       4                   0    0      False
24 2019-03-04   20        22       0                   0    4      False
25 2019-03-05   24        20       8                   0    0      False
26 2019-03-06   32        12       4                   0    0      False
27 2019-03-07   41        17       4                   0    0      False
28 2019-03-08   28        19       0                   0    4      False
29 2019-03-09   28        19       5                   0    0      False
..        ...  ...       ...     ...                 ...  ...        ...
57 2019-04-06   41        26       0                   0    0      False
58 2019-04-07   35        21       0                   0    0      False
59 2019-04-08   52        26       0                   0    0      False
60 2019-04-09   56        36       0                   0    4      False
61 2019-04-10   32        30       0                   0    4      False
62 2019-04-11   32        38       0                   0    4      False
63 2019-04-12   48        13       0                   0    0      False
64 2019-04-13   42        16       0                   0    0      False
65 2019-04-14   43        19       0                   0    5      False
66 2019-04-15   27        25       0                   0    0      False
67 2019-04-16   36        17       4                   0    4      False
68 2019-04-17   46        25       0                   0    0      False
69 2019-04-18   40        19       4                   0    4      False
70 2019-04-19   37        23       9                   0    0      False
71 2019-04-20   28        32       0                   0    0      False
72 2019-04-21   34        25       5                   0    0      False
73 2019-04-22   38        36       0                   0    0      False
74 2019-04-23   44        19       4                   0    0      False
75 2019-04-24   49        24       0                   0    4      False
76 2019-04-25   31        20       0                   0    0      False
77 2019-04-26   26        18       0                   0    0      False
78 2019-04-27   39        28       0                   4    0      False
79 2019-04-28   26        21       0                   0    5      False
80 2019-04-29   44        20       0                   0    0      False
81 2019-04-30   27        12       0                   0    0      False
82 2019-05-01   20        13       0                   0    0      False
83 2019-05-02   25        16       0                   0    0      False
84 2019-05-03   30        10       0                   0    0      False
85 2019-05-04   38        18       0                   0    0      False
86 2019-05-05   14        14       9                   0    0      False

[87 rows x 7 columns]

In [55]:
pytrends = TrendReq(hl='en-US', tz=360)
queries_list = ['shiv sena', 'Telugu desam', 'TRS', 'communist']
queries_list
pytrends.build_payload(queries_list, timeframe='today 3-m', geo='IN', gprop='news')
Party_group2 = pytrends.interest_over_time()
Party_group2.reset_index(level=0, inplace=True)
Party_group2

         date  shiv sena  Telugu desam  TRS  communist  isPartial
0  2019-02-08         42             0    0         21      False
1  2019-02-09          0             0   23          0      False
2  2019-02-10          0             0    0          0      False
3  2019-02-11         32             0    0          0      False
4  2019-02-12          0             0    0          0      False
5  2019-02-13         41             0    0          0      False
6  2019-02-14        100             0   19          0      False
7  2019-02-15         18             0    0         18      False
8  2019-02-16         19             0    0          0      False
9  2019-02-17          0             0    0          0      False
10 2019-02-18         30             0    0          0      False
11 2019-02-19         22             0    0         22      False
12 2019-02-20         21             0    0          0      False
13 2019-02-21         20             0    0          0      False
14 2019-02-22          0             0   21          0      False
15 2019-02-23         22             0   22          0      False
16 2019-02-24          0             0    0          0      False
17 2019-02-25          0             0   22          0      False
18 2019-02-26          0             0   14          0      False
19 2019-02-27         14             0    0          0      False
20 2019-02-28          0             0    0          0      False
21 2019-03-01          0             0   18          0      False
22 2019-03-02          0             0    0          0      False
23 2019-03-03          0             0    0          0      False
24 2019-03-04         22             0    0          0      False
25 2019-03-05          0             0    0          0      False
26 2019-03-06          0             0    0          0      False
27 2019-03-07          0             0    0          0      False
28 2019-03-08          0             0    0          0      False
29 2019-03-09         26             0   25          0      False
..        ...        ...           ...  ...        ...        ...
57 2019-04-06         24             0    0          0      False
58 2019-04-07         25             0   25         25      False
59 2019-04-08          0            24    0          0      False
60 2019-04-09         25            25    0          0      False
61 2019-04-10          0             0    0          0      False
62 2019-04-11          0             0   22          0      False
63 2019-04-12          0             0    0          0      False
64 2019-04-13          0             0    0          0      False
65 2019-04-14          0             0    0          0      False
66 2019-04-15          0             0    0          0      False
67 2019-04-16          0             0   23          0      False
68 2019-04-17         35             0    0          0      False
69 2019-04-18          0             0    0          0      False
70 2019-04-19         76             0    0          0      False
71 2019-04-20         25             0    0          0      False
72 2019-04-21          0             0    0         24      False
73 2019-04-22          0             0    0          0      False
74 2019-04-23          0             0    0          0      False
75 2019-04-24         24             0    0          0      False
76 2019-04-25          0             0    0         25      False
77 2019-04-26         24             0   24          0      False
78 2019-04-27          0             0    0          0      False
79 2019-04-28         25             0    0          0      False
80 2019-04-29         22            22    0          0      False
81 2019-04-30          0             0   23          0      False
82 2019-05-01         24             0    0          0      False
83 2019-05-02          0             0   22          0      False
84 2019-05-03         21             0   22          0      False
85 2019-05-04          0             0    0          0      False
86 2019-05-05          0             0    0          0      False

[87 rows x 6 columns]

In [57]:
pytrends = TrendReq(hl='en-US', tz=360)
queries_list = ['Narendra Modi', 'Rahul Gandhi', 'MK Stalin', 'Mamata banerjee', 'Navin Patnaik']
queries_list
pytrends.build_payload(queries_list, timeframe='today 3-m', geo='IN', gprop='news')
Party_Leader1 = pytrends.interest_over_time()
Party_Leader1.reset_index(level=0, inplace=True)
Party_Leader1

,date,Narendra Modi,Rahul Gandhi,MK Stalin,Mamata banerjee,Navin Patnaik,isPartial
0,2019-02-08,9,22,0,9,0,False
1,2019-02-09,10,30,0,10,0,False
2,2019-02-10,30,20,0,0,0,False
3,2019-02-11,9,13,0,0,0,False
4,2019-02-12,13,18,0,9,0,False
5,2019-02-13,13,9,0,9,0,False
6,2019-02-14,12,16,0,8,0,False
7,2019-02-15,52,19,0,0,0,False
8,2019-02-16,39,12,0,8,0,False
9,2019-02-17,34,21,0,9,0,False
10,2019-02-18,12,12,0,8,0,False
11,2019-02-19,13,9,0,0,0,False
12,2019-02-20,22,0,0,9,0,False
13,2019-02-21,8,8,0,8,0,False
14,2019-02-22,18,13,0,27,0,False
15,2019-02-23,14,19,0,0,0,False
16,2019-02-24,27,27,0,0,0,False
17,2019-02-25,18,9,0,9,0,False
18,2019-02-26,31,6,0,6,0,False
19,2019-02-27,15,30,0,6,0,False
20,2019-02-28,31,23,0,0,0,False
21,2019-03-01,27,11,0,0,0,False
22,2019-03-02,27,13,0,9,0,False
23,2019-03-03,19,14,0,0,0,False
24,2019-03-04,23,32,0,0,0,False
25,2019-03-05,18,18,9,0,0,False
26,2019-03-06,27,19,0,0,0,False
27,2019-03-07,9,24,0,0,0,False
28,2019-03-08,15,59,0,0,0,False
29,2019-03-09,26,22,0,11,0,False
...,...,...,...,...,...,...,...
57,2019-04-06,40,15,0,10,0,False
58,2019-04-07,27,59,0,11,0,False
59,2019-04-08,20,39,0,10,0,False
60,2019-04-09,31,30,0,0,0,False
61,2019-04-10,29,34,0,10,0,False
62,2019-04-11,37,37,0,0,0,False
63,2019-04-12,30,20,0,0,0,False
64,2019-04-13,37,21,0,0,0,False
65,2019-04-14,27,16,0,0,0,False
66,2019-04-15,20,14,0,0,0,False
67,2019-04-16,29,24,0,10,0,False
68,2019-04-17,29,14,0,0,0,False
69,2019-04-18,19,29,0,0,0,False
70,2019-04-19,16,37,0,0,0,False
71,2019-04-20,21,69,0,0,0,False
72,2019-04-21,21,31,0,0,0,False
73,2019-04-22,19,100,0,9,0,False
74,2019-04-23,10,38,0,0,0,False
75,2019-04-24,25,35,10,10,0,False
76,2019-04-25,26,46,0,10,0,False
77,2019-04-26,50,20,0,10,0,False
78,2019-04-27,20,20,0,0,0,False
79,2019-04-28,66,38,0,0,0,False
80,2019-04-29,18,18,0,0,0,False
81,2019-04-30,28,24,0,0,0,False
82,2019-05-01,15,35,0,0,0,False
83,2019-05-02,19,19,0,0,0,False
84,2019-05-03,27,27,0,9,0,False
85,2019-05-04,21,21,0,0,0,False
86,2019-05-05,21,47,0,0,0,False

In [60]:
pytrends = TrendReq(hl='en-US', tz=360)
queries_list = ['Uddhav Thackeray', 'N. Chandrababu Naidu', 'K. Chandrashekar Rao', 'Sitaram Yechury']
queries_list
pytrends.build_payload(queries_list, timeframe='today 3-m', geo='IN', gprop='news')
Party_Leader2 = pytrends.interest_over_time()
Party_Leader2.reset_index(level=0, inplace=True)
Party_Leader2

,date,Uddhav Thackeray,N. Chandrababu Naidu,K. Chandrashekar Rao,Sitaram Yechury,isPartial
0,2019-02-08,0,0,0,0,False
1,2019-02-09,0,0,0,0,False
2,2019-02-10,0,0,0,0,False
3,2019-02-11,0,0,0,0,False
4,2019-02-12,0,0,0,0,False
5,2019-02-13,0,0,0,0,False
6,2019-02-14,0,0,0,0,False
7,2019-02-15,0,0,0,0,False
8,2019-02-16,0,0,0,0,False
9,2019-02-17,0,0,0,0,False
10,2019-02-18,0,0,0,0,False
11,2019-02-19,84,0,0,0,False
12,2019-02-20,0,0,0,0,False
13,2019-02-21,0,0,0,0,False
14,2019-02-22,0,0,0,0,False
15,2019-02-23,0,0,0,0,False
16,2019-02-24,0,0,0,0,False
17,2019-02-25,0,0,0,0,False
18,2019-02-26,0,0,0,0,False
19,2019-02-27,55,0,0,0,False
20,2019-02-28,0,0,0,0,False
21,2019-03-01,0,0,0,0,False
22,2019-03-02,0,0,0,0,False
23,2019-03-03,0,0,0,0,False
24,2019-03-04,0,0,0,0,False
25,2019-03-05,0,0,0,0,False
26,2019-03-06,0,0,0,0,False
27,2019-03-07,87,0,0,0,False
28,2019-03-08,0,0,0,0,False
29,2019-03-09,0,0,0,0,False
...,...,...,...,...,...,...
57,2019-04-06,0,0,0,0,False
58,2019-04-07,0,0,0,0,False
59,2019-04-08,0,0,0,0,False
60,2019-04-09,0,0,0,0,False
61,2019-04-10,91,0,0,0,False
62,2019-04-11,0,0,0,0,False
63,2019-04-12,0,0,0,0,False
64,2019-04-13,100,0,0,0,False
65,2019-04-14,0,0,0,0,False
66,2019-04-15,0,0,0,0,False
67,2019-04-16,0,0,0,0,False
68,2019-04-17,0,0,0,0,False
69,2019-04-18,0,0,0,0,False
70,2019-04-19,0,0,0,0,False
71,2019-04-20,0,0,0,0,False
72,2019-04-21,0,0,0,0,False
73,2019-04-22,0,0,0,0,False
74,2019-04-23,0,0,0,0,False
75,2019-04-24,0,0,0,0,False
76,2019-04-25,0,0,0,0,False
77,2019-04-26,0,0,0,0,False
78,2019-04-27,0,0,0,0,False
79,2019-04-28,0,0,0,0,False
80,2019-04-29,0,0,0,0,False
81,2019-04-30,0,0,0,0,False
82,2019-05-01,0,0,0,0,False
83,2019-05-02,0,0,0,0,False
84,2019-05-03,0,0,0,0,False
85,2019-05-04,0,0,0,0,False
86,2019-05-05,0,0,0,0,False

In [66]:
# Merge Party_Leader1 and Party_Leader2
Party_Leader = pd.merge(Party_Leader1, Party_Leader2, how = 'outer' )
Party_Leader

,date,Narendra Modi,Rahul Gandhi,MK Stalin,Mamata banerjee,Navin Patnaik,isPartial,Uddhav Thackeray,N. Chandrababu Naidu,K. Chandrashekar Rao,Sitaram Yechury
0,2019-02-08,9,22,0,9,0,False,0,0,0,0
1,2019-02-09,10,30,0,10,0,False,0,0,0,0
2,2019-02-10,30,20,0,0,0,False,0,0,0,0
3,2019-02-11,9,13,0,0,0,False,0,0,0,0
4,2019-02-12,13,18,0,9,0,False,0,0,0,0
5,2019-02-13,13,9,0,9,0,False,0,0,0,0
6,2019-02-14,12,16,0,8,0,False,0,0,0,0
7,2019-02-15,52,19,0,0,0,False,0,0,0,0
8,2019-02-16,39,12,0,8,0,False,0,0,0,0
9,2019-02-17,34,21,0,9,0,False,0,0,0,0
10,2019-02-18,12,12,0,8,0,False,0,0,0,0
11,2019-02-19,13,9,0,0,0,False,84,0,0,0
12,2019-02-20,22,0,0,9,0,False,0,0,0,0
13,2019-02-21,8,8,0,8,0,False,0,0,0,0
14,2019-02-22,18,13,0,27,0,False,0,0,0,0
15,2019-02-23,14,19,0,0,0,False,0,0,0,0
16,2019-02-24,27,27,0,0,0,False,0,0,0,0
17,2019-02-25,18,9,0,9,0,False,0,0,0,0
18,2019-02-26,31,6,0,6,0,False,0,0,0,0
19,2019-02-27,15,30,0,6,0,False,55,0,0,0
20,2019-02-28,31,23,0,0,0,False,0,0,0,0
21,2019-03-01,27,11,0,0,0,False,0,0,0,0
22,2019-03-02,27,13,0,9,0,False,0,0,0,0
23,2019-03-03,19,14,0,0,0,False,0,0,0,0
24,2019-03-04,23,32,0,0,0,False,0,0,0,0
25,2019-03-05,18,18,9,0,0,False,0,0,0,0
26,2019-03-06,27,19,0,0,0,False,0,0,0,0
27,2019-03-07,9,24,0,0,0,False,87,0,0,0
28,2019-03-08,15,59,0,0,0,False,0,0,0,0
29,2019-03-09,26,22,0,11,0,False,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
57,2019-04-06,40,15,0,10,0,False,0,0,0,0
58,2019-04-07,27,59,0,11,0,False,0,0,0,0
59,2019-04-08,20,39,0,10,0,False,0,0,0,0
60,2019-04-09,31,30,0,0,0,False,0,0,0,0
61,2019-04-10,29,34,0,10,0,False,91,0,0,0
62,2019-04-11,37,37,0,0,0,False,0,0,0,0
63,2019-04-12,30,20,0,0,0,False,0,0,0,0
64,2019-04-13,37,21,0,0,0,False,100,0,0,0
65,2019-04-14,27,16,0,0,0,False,0,0,0,0
66,2019-04-15,20,14,0,0,0,False,0,0,0,0
67,2019-04-16,29,24,0,10,0,False,0,0,0,0
68,2019-04-17,29,14,0,0,0,False,0,0,0,0
69,2019-04-18,19,29,0,0,0,False,0,0,0,0
70,2019-04-19,16,37,0,0,0,False,0,0,0,0
71,2019-04-20,21,69,0,0,0,False,0,0,0,0
72,2019-04-21,21,31,0,0,0,False,0,0,0,0
73,2019-04-22,19,100,0,9,0,False,0,0,0,0
74,2019-04-23,10,38,0,0,0,False,0,0,0,0
75,2019-04-24,25,35,10,10,0,False,0,0,0,0
76,2019-04-25,26,46,0,10,0,False,0,0,0,0
77,2019-04-26,50,20,0,10,0,False,0,0,0,0
78,2019-04-27,20,20,0,0,0,False,0,0,0,0
79,2019-04-28,66,38,0,0,0,False,0,0,0,0
80,2019-04-29,18,18,0,0,0,False,0,0,0,0
81,2019-04-30,28,24,0,0,0,False,0,0,0,0
82,2019-05-01,15,35,0,0,0,False,0,0,0,0
83,2019-05-02,19,19,0,0,0,False,0,0,0,0
84,2019-05-03,27,27,0,9,0,False,0,0,0,0
85,2019-05-04,21,21,0,0,0,False,0,0,0,0
86,2019-05-05,21,47,0,0,0,False,0,0,0,0

In [64]:
# Merge Party_group1 and Party_group2
Party_Group = pd.merge(Party_group1, Party_group2, how = 'outer' )
Party_Group

,date,BJP,Congress,AIADMK,trinamool congress,BJD,isPartial,shiv sena,Telugu desam,TRS,communist
0,2019-02-08,13,8,0,0,0,False,42,0,0,21
1,2019-02-09,19,17,0,0,0,False,0,0,23,0
2,2019-02-10,16,13,0,0,0,False,0,0,0,0
3,2019-02-11,18,18,0,0,0,False,32,0,0,0
4,2019-02-12,28,14,4,0,0,False,0,0,0,0
5,2019-02-13,25,21,4,0,0,False,41,0,0,0
6,2019-02-14,27,12,4,0,0,False,100,0,19,0
7,2019-02-15,15,7,3,0,0,False,18,0,0,18
8,2019-02-16,19,14,3,0,0,False,19,0,0,0
9,2019-02-17,7,13,0,0,0,False,0,0,0,0
10,2019-02-18,20,9,11,0,0,False,30,0,0,0
11,2019-02-19,33,17,6,0,0,False,22,0,0,22
12,2019-02-20,21,15,0,0,4,False,21,0,0,0
13,2019-02-21,24,11,4,0,0,False,20,0,0,0
14,2019-02-22,16,19,4,0,4,False,0,0,21,0
15,2019-02-23,24,22,6,4,0,False,22,0,22,0
16,2019-02-24,12,10,0,0,0,False,0,0,0,0
17,2019-02-25,14,14,0,0,0,False,0,0,22,0
18,2019-02-26,11,7,0,0,3,False,0,0,14,0
19,2019-02-27,8,14,5,0,0,False,14,0,0,0
20,2019-02-28,10,20,0,0,0,False,0,0,0,0
21,2019-03-01,7,8,3,0,0,False,0,0,18,0
22,2019-03-02,14,18,4,0,4,False,0,0,0,0
23,2019-03-03,11,13,4,0,0,False,0,0,0,0
24,2019-03-04,20,22,0,0,4,False,22,0,0,0
25,2019-03-05,24,20,8,0,0,False,0,0,0,0
26,2019-03-06,32,12,4,0,0,False,0,0,0,0
27,2019-03-07,41,17,4,0,0,False,0,0,0,0
28,2019-03-08,28,19,0,0,4,False,0,0,0,0
29,2019-03-09,28,19,5,0,0,False,26,0,25,0
...,...,...,...,...,...,...,...,...,...,...,...
57,2019-04-06,41,26,0,0,0,False,24,0,0,0
58,2019-04-07,35,21,0,0,0,False,25,0,25,25
59,2019-04-08,52,26,0,0,0,False,0,24,0,0
60,2019-04-09,56,36,0,0,4,False,25,25,0,0
61,2019-04-10,32,30,0,0,4,False,0,0,0,0
62,2019-04-11,32,38,0,0,4,False,0,0,22,0
63,2019-04-12,48,13,0,0,0,False,0,0,0,0
64,2019-04-13,42,16,0,0,0,False,0,0,0,0
65,2019-04-14,43,19,0,0,5,False,0,0,0,0
66,2019-04-15,27,25,0,0,0,False,0,0,0,0
67,2019-04-16,36,17,4,0,4,False,0,0,23,0
68,2019-04-17,46,25,0,0,0,False,35,0,0,0
69,2019-04-18,40,19,4,0,4,False,0,0,0,0
70,2019-04-19,37,23,9,0,0,False,76,0,0,0
71,2019-04-20,28,32,0,0,0,False,25,0,0,0
72,2019-04-21,34,25,5,0,0,False,0,0,0,24
73,2019-04-22,38,36,0,0,0,False,0,0,0,0
74,2019-04-23,44,19,4,0,0,False,0,0,0,0
75,2019-04-24,49,24,0,0,4,False,24,0,0,0
76,2019-04-25,31,20,0,0,0,False,0,0,0,25
77,2019-04-26,26,18,0,0,0,False,24,0,24,0
78,2019-04-27,39,28,0,4,0,False,0,0,0,0
79,2019-04-28,26,21,0,0,5,False,25,0,0,0
80,2019-04-29,44,20,0,0,0,False,22,22,0,0
81,2019-04-30,27,12,0,0,0,False,0,0,23,0
82,2019-05-01,20,13,0,0,0,False,24,0,0,0
83,2019-05-02,25,16,0,0,0,False,0,0,22,0
84,2019-05-03,30,10,0,0,0,False,21,0,22,0
85,2019-05-04,38,18,0,0,0,False,0,0,0,0
86,2019-05-05,14,14,9,0,0,False,0,0,0,0