In [5]:
import pandas as pd
from sqlalchemy import create_engine, inspect
import os
import pyodbc

In [6]:
partysummarypath = os.path.join('output','PartySummary.csv')
partypropertiespath = os.path.join('output', 'PartyProperties.csv')
sentimentscorespath = os.path.join('output', 'SentimentScores.csv')
indiageneralelectionpath = os.path.join('output', 'IndianGeneralElectionData.csv')
partyleaderratingspath = os.path.join('output', 'Party_Leader_Ratings_googleTrends.csv')
partyratingspath = os.path.join('output', 'Party_Rating_googleTrends.csv')

In [7]:
# database_path = os.path.join('output','IndiaElectionDB.sqlite')

In [8]:
# engine = create_engine(f"sqlite:///{database_path}")

In [9]:
partysummarydf = pd.read_csv(partysummarypath, encoding = "ISO-8859-1")
partypropertiesdf = pd.read_csv(partypropertiespath, encoding = "ISO-8859-1")
sentimentscores = pd.read_csv(sentimentscorespath, encoding = "ISO-8859-1")
indiageneralelection = pd.read_csv(indiageneralelectionpath, encoding = "ISO-8859-1")
partyleaderratingspath = pd.read_csv(partyleaderratingspath, encoding = "ISO-8859-1")
partyratingspath = pd.read_csv(partyratingspath, encoding = "ISO-8859-1")

In [10]:
#Create SQL Engine
rds_connection_string = "root:Soms@1411@localhost:3306/IndianGeneralElection2014"
engine = create_engine(f'mysql://{rds_connection_string}')
engine.table_names()

['IndiaVotes_PC_All_States_2014']

In [17]:
partysummarydf.to_sql(name='PartySummary', con=engine, if_exists='append', index=False)
# partypropertiesdf.to_sql(name='PartyProperties', con=engine, if_exists='append', index=False)
sentimentscores.to_sql(name='SentimentScores', con=engine, if_exists='append', index=False)
indiageneralelection.to_sql(name='IndiaGeneralElection', con=engine, if_exists='append', index=False)
partyleaderratingspath.to_sql(name='PartyLeaderRatings', con=engine, if_exists='append', index=False)
partyratingspath.to_sql(name='PartyRatings', con=engine, if_exists='append', index=False)

In [20]:
pd.read_sql('SELECT * from IndiaGeneralElection', con=engine).head()

,Unnamed: 0,PC Name,No,Type,State,Winning Candidate,Party,Electors,Votes,Turnout,Margin,Margin %,Code
0,0,Adilabad,1,ST,Telangana,Godam Nagesh,Telangana Rashtra Samithi,1386233,1045839,75.4 %,171290,16.4%,TRS
1,1,Agra,18,SC,Uttar Pradesh [2000 Onwards],Dr. Ram Shankar Katheria,Bharatiya Janta Party,1814739,1070400,59.0 %,300263,28.1%,BJP
2,2,Ahmadnagar,37,GEN,Maharashtra,Gandhi Dilipkumar Mansukhlal,Bharatiya Janta Party,1699408,1062318,62.5 %,209122,19.7%,BJP
3,3,Ahmedabad East,7,GEN,Gujarat,Paresh Rawal,Bharatiya Janta Party,1601832,985525,61.5 %,326633,33.1%,BJP
4,4,Ahmedabad West,8,SC,Gujarat,Dr. Kirit P Solanki,Bharatiya Janta Party,1534400,964609,62.9 %,320311,33.2%,BJP

In [19]:
pd.read_sql('SELECT * from PartyLeaderRatings', con=engine).head()

,Code,2019-02-08 00:00:00,2019-02-09 00:00:00,2019-02-10 00:00:00,2019-02-11 00:00:00,2019-02-12 00:00:00,2019-02-13 00:00:00,2019-02-14 00:00:00,2019-02-15 00:00:00,2019-02-16 00:00:00,...,2019-04-26 00:00:00,2019-04-27 00:00:00,2019-04-28 00:00:00,2019-04-29 00:00:00,2019-04-30 00:00:00,2019-05-01 00:00:00,2019-05-02 00:00:00,2019-05-03 00:00:00,2019-05-04 00:00:00,2019-05-05 00:00:00
0,BJP,9,10,30,9,13,13,12,52,39,...,50,20,66,18,28,15,19,27,21,21
1,INC,22,30,20,13,18,9,16,19,12,...,20,20,38,18,24,35,19,27,21,47
2,AIADMK,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,AITC,9,10,0,0,9,9,8,0,8,...,10,0,0,0,0,0,0,9,0,0
4,BJD,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0